export const en = {
  siteName: "Hantavirus.Homes",
  nav: {
    home: "Home",
    news: "News",
    reference: "Reference",
    map: "Map",
    about: "About",
    methodology: "Methodology",
    premium: "Pro Access",
    support: "Support",
  },
  home: {
    title: "Hantavirus.Homes",
    subtitle:
      "Global updates, a simple map, and practical explainers. Content is informational and not medical advice.",
    latestUpdates: "Latest updates",
    quickCards: {
      whatIs: { title: "What is hantavirus?", desc: "Overview, types, and key facts" },
      symptoms: { title: "Symptoms", desc: "Early signs and when to seek help" },
      prevention: { title: "Prevention", desc: "How to protect yourself" },
      faq: { title: "FAQ", desc: "Common questions answered" },
    },
  },
  common: {
    dailyDigest: "Daily digest",
    readMore: "Read more",
    source: "Source",
  },
  about: {
    p1: "Hantavirus.Homes is a project focused on verified, source-linked hantavirus updates and practical explainers.",
    p2: "Content is informational and may contain errors. It does not replace professional medical advice.",
  },
  map: {
    details: "Details",
    endemic: "Endemic",
    status: "Status",
    signals: "Signals (mentions)",
    casesTotal: "Total mentions",
    fatalityRate: "Fatality rate",
    period: "Period",
    updated: "Updated",
    sources: "Sources",
    relatedNews: "Related news",
    relatedNewsEmpty: "No related news found for this country yet.",
    openArticle: "Open article",
    confidence: "Confidence",
    confidenceLow: "Low",
    confidenceMedium: "Medium",
    confidenceHigh: "High",
    clearSelection: "Clear selection",
    clickPrompt: "Click a country or pin on the map to show details.",
    mvpNote: "Data based on online signals and official reports.",
    yes: "Yes",
    no: "No",
    unknown: "Unknown",
    searchPlaceholder: "Search country...",
    allRiskLevels: "All Risk Levels",
    riskLevel: "Risk Level",
    viralStrains: "Viral Strains",
    primaryHosts: "Primary Hosts (Rodents)",
    transmissionPath: "Transmission Path",
    preventionRecs: "Prevention Recommendations",
    typicalSymptoms: "Typical Symptoms",
    availableDiagnostics: "Available Diagnostics",
    mortalityContext: "Mortality Context",
    localAuthority: "Local Authority",
    liveMentions: "Live Signals",
    activityTrend: "7-Day Activity Trend",
    shareReport: "Share Report",
    copied: "Copied!",
    downloadReport: "Download Report (TXT)",
    proApi: "Professional API Access",
    supportProject: "Support Project",
    partnership: "Partnership & Data",
  },
};
