export const ru = {
  siteName: "Hantavirus.Homes",
  nav: {
    home: "Главная",
    news: "Новости",
    reference: "Справочник",
    map: "Карта",
    about: "О проекте",
    methodology: "Методология",
    premium: "Про-доступ",
    support: "Поддержка",
  },
  home: {
    title: "Hantavirus.Homes",
    subtitle:
      "Глобальные обновления, простая карта и практические объяснения. Контент информационный и не является медицинской консультацией.",
    latestUpdates: "Последние обновления",
    quickCards: {
      whatIs: { title: "Что такое хантавирус?", desc: "Обзор, типы и ключевые факты" },
      symptoms: { title: "Симптомы", desc: "Ранние признаки и когда обращаться за помощью" },
      prevention: { title: "Профилактика", desc: "Как защитить себя" },
      faq: { title: "FAQ", desc: "Ответы на распространённые вопросы" },
    },
  },
  common: {
    dailyDigest: "Ежедневный дайджест",
    readMore: "Читать дальше",
    source: "Источник",
  },
  about: {
    p1: "Hantavirus.Homes — это проект, посвященный проверенным обновлениям о хантавирусе со ссылками на источники и практическим объяснениям.",
    p2: "Контент носит информационный характер и может содержать ошибки. Он не заменяет профессиональную медицинскую консультацию.",
  },
  map: {
    details: "Детали",
    endemic: "Эндемичный",
    status: "Статус",
    signals: "Сигналы (упоминания)",
    casesTotal: "Всего упоминаний",
    fatalityRate: "Летальность",
    period: "Период",
    updated: "Обновлено",
    sources: "Источники",
    relatedNews: "Новости по стране",
    relatedNewsEmpty: "Пока не найдено релевантных новостей по этой стране.",
    openArticle: "Открыть статью",
    confidence: "Достоверность",
    confidenceLow: "Низкая",
    confidenceMedium: "Средняя",
    confidenceHigh: "Высокая",
    clearSelection: "Сбросить выбор",
    clickPrompt: "Нажмите на страну или метку на карте для деталей.",
    mvpNote: "Данные основаны на упоминаниях в сети и официальных отчетах.",
    yes: "Да",
    no: "Нет",
    unknown: "Неизвестно",
    searchPlaceholder: "Поиск страны...",
    allRiskLevels: "Все уровни риска",
    riskLevel: "Уровень риска",
    viralStrains: "Штаммы вируса",
    primaryHosts: "Переносчики (грызуны)",
    transmissionPath: "Путь передачи",
    preventionRecs: "Рекомендации по профилактике",
    typicalSymptoms: "Типичные симптомы",
    availableDiagnostics: "Диагностика",
    mortalityContext: "Контекст летальности",
    localAuthority: "Местное ведомство",
    liveMentions: "Живые сигналы",
    activityTrend: "Тренд активности за 7 дней",
    shareReport: "Поделиться отчетом",
    copied: "Скопировано!",
    downloadReport: "Скачать отчет (TXT)",
    proApi: "Доступ к профессиональному API",
    supportProject: "Поддержать проект",
    partnership: "Партнерство и данные",
  },
};
